spring:
  application:
    name: sistemas.vendas
  datasource:
    url: jdbc:postgresql://localhost:5434/loja
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
server:
    port: 8081
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expire-lenght: 3600000